### ISSUE TITLE
In professional identification information for Healthcare Professional error message is confusing

### ISSUE THREAD

**Issue by rajdarshanreddy** [biztek/drivers-license-input#15]
Steps to recreate
-  Open professional identification information for Healthcare Professional and select AZ state
-  Enter invalid Driver license number
-  Error message for driver license correct format is getting displayed to enter in `Drivers License should have at least 1 Alpha + 1-8 Numeric 2 Alpha + 2-5 Numeric 9 Numeric`
-  Error message  should be displayed  as   1 Alpha + 1-8 Numeric or 2 Alpha + 2-5 Numeric or 9 Numeric
![image](https://cloud.githubusercontent.com/assets/20438491/19881554/c02ba15e-a02c-11e6-9f27-a8b75cac05a5.png)

**Comment by cherukumilli** [comment]
@rajdarshanreddy 
Is this also fixed and integrated with the ui?
If so, please mark it for testing.
