### ISSUE TITLE
remove unwanted lines of code mentioned below in .travis.yml

### ISSUE THREAD

**Issue by rajkumarajce** [biztek/drivers-license-input#4]
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install iron-icon#v1.0.9
- export DISPLAY=:99.0

Move iron icon to bower.json dependencies

**Comment by rajdarshanreddy** [comment]
- please refer https://youtu.be/afy_EEq_4Go?t=6m14s
- there is a problem with iron icon element, this version on it bug free.
- this is used to set up a fake DISPLAY
